---
title: "HW3"
output: html_notebook
---

```{r}
install.packages("tidyverse")
install.packages("skimr")

```
```{r}
library(tidyverse)
library(skimr)

```

```{r}
d0 <- read_csv("pulse2021_puf_33_d1.csv")
```

```{r}
d1 <- select(d0, WEEK, EST_MSA, REGION, TBIRTH_YEAR, EGENDER, RHISPANIC,
   RRACE, EEDUC, MS, THHLD_NUMADLT, THHLD_NUMPER, DOSES, GETVACRV,
   WHYNOT1, WHYNOT2, WHYNOT3, WHYNOT4, WHYNOT5, WHYNOT6, WHYNOT7,
   WHYNOT8, WHYNOT9, WHYNOT10, WHYNOT11, WHYNOTB1, WHYNOTB2, WHYNOTB3,
   WHYNOTB4, WHYNOTB5, WHYNOTB6, HADCOVID, ANYWORK, EIPRV)
```
```{r}
d1$MS = ifelse(d1$MS == -99, NA, d1$MS)
d1[d1 == -99] <- 0
d1[d1 == -88] <- 0 # Probably should be NA.
```
```{r}
d1
```



```{r}
skim(d1)
```
```{r}
write_csv(d1, "pulse2021_puf_33_d1.csv")
```
```{r}
d1$RRACE <- factor(d1$RRACE,levels=c(1,2,3,4),labels=c("White","Black","Asian","Other"))
```


```{r}
d1$EGENDER <- factor(d1$EGENDER,levels=c(1,2),labels=c("Male","Female"))
```

```{r}
d1$RHISPANIC <- factor(d1$RHISPANIC,levels=c(1,2),labels=c("Not Hispanic","Hispanic"))
```
```{r}
d1$GETVACRV <- factor(d1$GETVACRV,levels=c(1,2,3,4,5),labels=c("Definitely","Probably","Not sure","Probably Not","Definitely Not"))
```
```{r}
d1$DOSES <- factor(d1$DOSES,levels=c(1,2),labels=c("1","2"))
```

```{r}
d1$EEDUC <- factor(d1$EEDUC,levels=c(1,2,3,4,5,6,7),labels=c("Less than High School","Some High School","High school Graduate","Some College","Associate Degree","Bachelor's Degree","Graduate Degree"))
```
```{r}
d1$MS <- factor(d1$MS,levels=c(1,2,3,4,5,6),labels=c("Now Married","Widowed","Divorced","Separated","Never Married","Data Not Available"))
```

##GRAPH 1
## Problem : What would be the Gender-wise distribution for individuals at different education levels?
```{r}
first <- ggplot(data = d1)+
  geom_bar(mapping = aes(x=d1$EGENDER))+
  facet_wrap(~d1$EEDUC, ncol=3)+
  labs(
    title = "Gender wise Distribution for Educational Attainment", 
    caption = "Bar Plot for Gender Wise Distribution for individuals at different education levels",
    x="Gender", 
    y="Count",
    legend=T
    )
```
```{r}
first
```

##GRAPH2
## Problem : What would be the gender & marital status wise distribution of doses received by our sample?
```{r}
second <- ggplot(data = d1)+
  geom_jitter(mapping = aes(x=d1$EGENDER,y=d1$DOSES))+
  facet_wrap(~d1$MS, ncol =  3)+
  labs(
    title = "Gender & Marital Status-wise Distribution of Doses Received", 
    caption="Jitter Plot of doses received by males & females wrt to their marital status",
    x="Gender", 
    y="Doses",
    legend=T
    )
```
```{r}
second
```

##GRAPH 3
## Problem : What would be the distribution of willingness of individuals to get the covid19 vaccine?
```{r}

third <- ggplot(data = d1, aes(x = GETVACRV))+
  geom_histogram(binwidth=0.5,color="red")+
  ggtitle("Distribution of willingness to get covid19 vaccine")+
  xlab("Intention on getting vaccine")+
  ylab("Count")

```
```{r}
third
```

